name: nodejs-feature-branch-workflow
on: 

# someone should call this
  workflow_call:
    inputs:
      project:
        description: 'Project name'
        required: true
        type: string
      component:
        description: 'Component name'
        required: true
        type: string
     
jobs:
  trigger:
    runs-on: self-hosted
    steps:
      - name: checkout or clone code
        uses: actions/checkout@v6

      - name: Read package.json version
        id: package-version
        run: |
          APP_VERSION=$(jq -r '.version' package.json)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          
      - name: check app version
        run: echo "$APP_VERSION"

      - name: install dependencies
        run: npm install

      - name: unit tests
        id: unit_tests
        run: npm test


      - name: sonar scan
        id: sonar_scan
        uses: SonarSource/sonarqube-scan-action@v8.2.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate check
        id: sonar_check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} 

      - name: Check Dependabot Alerts
        id: library_scan
        uses: spicyparrot/check-dependabot@v1.2.0
        with:
          github_personal_token: ${{ secrets.DEPENDABOT_TOKEN }}  
          severities: 'critical,high' 
          fail-on-alerts: 'true'  