name: nodejs-feature-branch-workflow
on: 

# someone should call this
  workflow_call:
    inputs:
      project:
        description: 'Project name'
        required: true
        type: string
      component:
        description: 'Component name'
        required: true
        type: string
     
jobs:
  trigger:
    runs-on: self-hosted
    steps:
      - name: checkout or clone code
        uses: actions/checkout@v6

      - name: Read package.json version
        id: package-version
        run: |
          APP_VERSION=$(jq -r '.version' package.json)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          
      - name: check app version
        run: echo "$APP_VERSION"

      - name: install dependencies
        run: npm install

      - name: unit tests
        id: unit_tests
        run: npm test